In [ ]:
!pip install transformers

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

In [ ]:
device='cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
device

'cuda'

In [ ]:
model="openai-community/gpt2-large"
tokenizer=AutoTokenizer.from_pretrained(model)

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

AutoModelForCausalLM:- is used for text generation

In [ ]:
model=AutoModelForCausalLM.from_pretrained(model).to(device)

model.safetensors:   0%|          | 0.00/3.25G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
input_text="I love machine learning"
max_length=128

input_ids=tokenizer(input_text,return_tensors="pt")

In [ ]:
input_ids

{'input_ids': tensor([[  40, 1842, 4572, 4673]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [ ]:
input_ids=input_ids['input_ids'].to(device)

In [ ]:
input_ids

tensor([[  40, 1842, 4572, 4673]], device='cuda:0')

Beam search

In [ ]:
output=model.generate(input_ids, max_length=max_length, num_beams=5, do_sample=False,no_repeat_ngram_size=2)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [ ]:
output

tensor([[   40,  1842,  4572,  4673,    11,   475,   314,  1101,   407,   257,
          4572, 22454,  1008,    13,   314,   836,   470,   760,   703,   284,
          1430,   257, 17019,  3127,    11,   290,   314,   423,   645,  1393,
           287,  1804,   523,    13,   198,   198,  1537,   314,   466,   760,
           257,  1256,   546,  1366,  3783,    11,   543,   318,   262,  2050,
           286,   703,  1366,   460,   307,   973,   284,   787,  1365,  5370,
            13,   554,   428,  1281,    11,   314,   765,   284,  2648,   617,
           286,   262,  1243,   314,  1053,  4499,   625,   262,  1613,  1178,
           812,    11,   355,   880,   355,   617,  9040,   290, 15910,   326,
           314,   779,   284,   651,   262,   749,   503,   286,   616,  1366,
          5519,     6,   670,    13,   770,  1281,   318,   407,  4001,   284,
           307,   257,  9815,  1351,   286,   477,   262,  4899,   290,  7605,
           345,   815,   760,    13,  5455,    11,  

In [ ]:


print(tokenizer.decode(output[0]))

I love machine learning, but I'm not a machine learner. I don't know how to program a neural network, and I have no interest in doing so.

But I do know a lot about data science, which is the study of how data can be used to make better decisions. In this post, I want to share some of the things I've learned over the past few years, as well as some tips and tricks that I use to get the most out of my data scientists' work. This post is not meant to be a comprehensive list of all the tools and techniques you should know. Instead, it's


Nuclear search(top-P)



In [ ]:

output=model.generate(input_ids, max_length=max_length, num_beams=5, do_sample=True,top_p=1)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [ ]:
output

tensor([[  40, 1842, 4572, 4673,   11,  475,  314, 1101,  407, 1654,  340,  338,
          262,  826, 2891,  329,  262, 1693,   13,  198,  198, 1532,  345,  821,
         4609,  287, 4572, 4673,  290,  765,  284, 2193,  517,  546,  340,   11,
         2198,  503,  262, 1708, 4133,   25,  198,  198, 2514, 2193,  517,  546,
         4572, 4673,   11, 2198,  503,  262, 1708, 4133,   25,  198,  198, 2514,
         2193,  517,  546, 4572, 4673,  290,  765,  284, 2193,  517,  546,  340,
           11, 2198,  503,  262, 1708, 4133,   25,  198,  198, 2514, 2193,  517,
          546, 4572, 4673,  290,  765,  284, 2193,  517,  546,  340,   11, 2198,
          503,  262, 1708, 4133,   25,  198,  198, 2514, 2193,  517,  546, 4572,
         4673,  290,  765,  284, 2193,  517,  546,  340,   11, 2198,  503,  262,
         1708, 4133,   25,  198,  198, 2514, 2193,  517]], device='cuda:0')

In [ ]:

tokenizer.decode(output[0])

"I love machine learning, but I'm not sure it's the right tool for the job.\n\nIf you're interested in machine learning and want to learn more about it, check out the following resources:\n\nTo learn more about machine learning, check out the following resources:\n\nTo learn more about machine learning and want to learn more about it, check out the following resources:\n\nTo learn more about machine learning and want to learn more about it, check out the following resources:\n\nTo learn more about machine learning and want to learn more about it, check out the following resources:\n\nTo learn more"